# Generated by Django 4.0.3 on 2022-03-16 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=8)),
                ('url', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[(' ', 'UNPROCESSED'), ('u', 'UNKNOWN'), ('e', 'ERROR'), ('s', 'SPAM'), ('j', 'JAM')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Binaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.TextField()),
                ('extracted', models.TextField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binaries', to='classifier.website')),
            ],
        ),
    ]
