# Generated by Django 4.0.3 on 2022-03-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Binaries',
            new_name='Binary',
        ),
        migrations.AlterModelOptions(
            name='binary',
            options={'verbose_name_plural': 'binaries'},
        ),
    ]
