# Generated by Django 4.0.3 on 2022-03-16 04:49

import classifier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_alter_website_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('u', 'UNPROCESSED'), ('u', 'UNKNOWN'), ('e', 'ERROR'), ('s', 'SPAM'), ('j', 'JAM')], default=classifier.models.Status['UNPROCESSED'], max_length=12),
        ),
    ]
