# Generated by Django 4.0.3 on 2022-03-16 05:12

import classifier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_website_code_alter_website_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('u', 'UNPROCESSED'), ('u', 'UNSURE'), ('e', 'ERROR'), ('s', 'SPAM'), ('j', 'JAM')], default=classifier.models.Status['UNPROCESSED'], max_length=12),
        ),
    ]
