# Generated by Django 4.0.3 on 2022-03-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_alter_website_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[(' ', 'unprocessed'), ('u', 'unsure'), ('e', 'error'), ('s', 'spam'), ('j', 'jam')], default=' ', max_length=12),
        ),
    ]
