# Generated by Django 4.0.3 on 2022-03-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_alter_website_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
